version: '3'

services:
  docupet-frontend:
    build:
      context: ./docupet
    ports:
      - "8080:8080"
    depends_on:
      - server-backend

  server-backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      APP_SECRET: b7de14c0b1b5e69088f33c2f9db30cf7
      DATABASE_URL: "mysql://andrewgphillips7:DocupetTest1!@oppenheim.iad1-mysql-e2-17b.dreamhost.com:3306/docupet?serverVersion=8.0.32&charset=utf8mb4"
