<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xoche5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xoche5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9xoche5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9xoche5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9xoche5\appDevDebugProjectContainer([
    'container.build_hash' => '9xoche5',
    'container.build_id' => '1ca68169',
    'container.build_time' => 1705287206,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xoche5');
